import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { DocumentStore } from "@/lib/documentStore";
import { LLMService } from "@/lib/llm";
import { WorkflowEngine } from "@/lib/workflowEngine";
import { SessionManager, Session } from "@/lib/sessionManager";
import { Document } from "@/types/document";
import { Workflow } from "@/lib/workflow";
import { DocumentCard } from "@/components/ui/DocumentCard";
import { DocumentTree } from "@/components/ui/DocumentTree";
import { toast } from "sonner";

export default function SessionWorkspace() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const [documentStore] = useState<DocumentStore>(
    new DocumentStore("./workspace"),
  );
  const [llmService] = useState<LLMService>(LLMService.fromEnv());
  const [sessionManager] = useState<SessionManager>(
    new SessionManager(documentStore, llmService),
  );
  const [session, setSession] = useState<Session | null>(null);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [selectedDocId, setSelectedDocId] = useState<string | undefined>();
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    if (sessionId) {
      loadSessionAndDocuments();
    }
  }, [sessionId]);

  const loadSessionAndDocuments = async () => {
    if (!sessionId) return;

    try {
      const loadedSession = await sessionManager.continueSession(sessionId);
      if (loadedSession) {
        setSession(loadedSession);
        const docs = await documentStore.listDocuments();
        setDocuments(docs);
      } else {
        toast.error("Session not found");
        navigate("/sessions");
      }
    } catch (error) {
      console.error("Failed to load session:", error);
      toast.error("Failed to load session");
      navigate("/sessions");
    }
  };

  const handleSendMessage = async () => {
    if (isProcessing || !session) return;

    const userInput = prompt("Enter task description:");
    if (!userInput) return;

    setIsProcessing(true);

    try {
      const tasks = parseTaskOutline(userInput);

      for (const task of tasks) {
        const newDoc: Document = {
          id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
          title: task.title,
          content: `Working on: ${task.title}\n\nDescription: ${task.description}\n\n---\n\n[Content will be generated by LLM]`,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          linkedDocumentIds: [],
          status: "in-progress",
        };

        await documentStore.saveDocument(newDoc);
      }

      toast.success(`Created ${tasks.length} tasks`);
      const docs = await documentStore.listDocuments();
      setDocuments(docs);
    } catch (error) {
      toast.error("Failed to create tasks");
    }

    setIsProcessing(false);
  };

  const parseTaskOutline = (
    task: string,
  ): Array<{
    id: string;
    title: string;
    description: string;
    dependencies: string[];
  }> => {
    const lines = task.split("\n").filter((line) => line.trim());
    const tasks: Array<{
      id: string;
      title: string;
      description: string;
      dependencies: string[];
    }> = [];

    lines.forEach((line, index) => {
      const trimmed = line.trim();
      if (trimmed.startsWith("-") || trimmed.startsWith("*")) {
        const title = trimmed.substring(1).trim();
        tasks.push({
          id: `task-${index}`,
          title: title,
          description: `Complete ${title}`,
          dependencies: index > 0 ? [`task-${index - 1}`] : [],
        });
      } else if (trimmed.length > 0) {
        tasks.push({
          id: `task-${index}`,
          title: trimmed,
          description: `Complete ${trimmed}`,
          dependencies: index > 0 ? [`task-${index - 1}`] : [],
        });
      }
    });

    return tasks;
  };

  const selectedDocument = documents.find((d) => d.id === selectedDocId);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-1">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
          <h2 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">
            Documents
          </h2>
          <DocumentTree
            documents={documents}
            selectedDocumentId={selectedDocId}
            onSelect={setSelectedDocId}
          />
        </div>
      </div>

      <div className="lg:col-span-2">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4 mb-6">
          <h2 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">
            Create New Task
          </h2>

          <div className="space-y-4">
            <textarea
              className="w-full p-3 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              rows={4}
              placeholder="Enter task description (one per line, optionally with - for subtasks)"
            />

            <button
              onClick={handleSendMessage}
              disabled={isProcessing}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors disabled:opacity-50"
            >
              {isProcessing ? "Processing..." : "Create Tasks"}
            </button>
          </div>
        </div>

        {selectedDocument && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
                {selectedDocument.title}
              </h2>
              <span
                className={`px-3 py-1 rounded-full text-sm font-medium ${
                  selectedDocument.status === "completed"
                    ? "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400"
                    : selectedDocument.status === "verified"
                      ? "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400"
                      : selectedDocument.status === "in-progress"
                        ? "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400"
                        : "bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300"
                }`}
              >
                {selectedDocument.status}
              </span>
            </div>

            <div className="prose dark:prose-invert max-w-none">
              <pre className="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300">
                {selectedDocument.content}
              </pre>
            </div>

            <div className="mt-4 pt-4 border-t dark:border-gray-700">
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Updated {new Date(selectedDocument.updatedAt).toLocaleString()}
              </p>
            </div>
          </div>
        )}

        {!selectedDocument && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 text-center">
            <p className="text-gray-500 dark:text-gray-400">
              Select a document to view details, or create a new task.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
